/* ==========================================================================
   maps-data.js — points of interest for the interactive vacation maps.
   Loaded by maps.html as window.MAPDATA.

   One entry per section (usually one per hotel/base the trip stays at). Each has:
     hotel : { name, lat, lng }          — the base; rendered as the 🏡 marker,
                                            and every POI's distance is measured from it.
     pois  : [ POI, ... ]

   POI fields:
     name       (string)  original/local name — keep it findable on a map
     category   (enum)     one of the keys in CATS (see maps.html): attraction |
                           restaurant | supermarket | nature | pool | animal |
                           museum | castle | scenic | park | shopping
     lat, lng   (number)   REAL coordinates. Do not guess — geocode/verify each.
     desc       (string)   one or two sentences, in the site's language
     hours      (string)   opening hours as text (verify close to travel)
     drive_min  (number)   driving minutes from the hotel (verify with a router)
     pass       (bool)     optional: covered by the trip's discount pass/city card
     closed_days (object) supermarkets/shopping only, e.g. {"Su":"closed"} or
                          {"Sa":"closed","Fr":"limited"}. WHICH day matters is
                          country-specific: Austria rests Sunday, Israel
                          Saturday, Saudi Arabia Friday, and Japan/the US not at
                          all. Set window.TRIPREGION (fetch_places.py writes it)
                          so the badge names the right day, or is hidden.

   NOTE: drive times and hours are estimates — re-verify before the trip.
   Delete the sample entries and fill with the real trip. Keep it valid JS.
   ========================================================================== */
/* Region settings: which day to badge, units, and nav apps that work here.
   Generated by scripts/fetch_places.py; edit if you hand-author this file. */
window.TRIPREGION = {"country":"AT","closed_days":["Su"],"short_days":[],"badge":true,
                     "distance":"km","temperature":"C","nav":["waze","gmaps"]};

window.MAPDATA = {

  /* ============================ Base 1 ============================ */
  base1: {
    hotel: { name: "Sample Hotel — Lakeside", lat: 47.3230, lng: 13.1330 },
    pois: [
      { name:"Old Town Square", category:"attraction", lat:47.3250, lng:13.1360, drive_min:5, pass:true,
        desc:"Historic pedestrian center with cafés, the market hall and the clock tower.",
        hours:"Mo-Sa 09:00-18:00", hours_note:"Square itself is always open" },
      { name:"Lake Promenade Beach", category:"nature", lat:47.3190, lng:13.1290, drive_min:4,
        desc:"Free swimming beach with a playground, boat rental and a shallow kids' area.",
        hours:"24/7", hours_note:"Lifeguard on duty Jul-Aug only" },
      { name:"Family Restaurant Seehof", category:"restaurant", lat:47.3241, lng:13.1345, drive_min:5,
        desc:"Lake-view terrace, schnitzel and wood-fired pizza, high chairs and a kids' menu.",
        hours:"Mo-Su 11:30-22:00", hours_note:"Kitchen closes 21:00" },
      { name:"SPAR Supermarkt", category:"supermarket", lat:47.3268, lng:13.1372, drive_min:6, closed_days:{Su:"closed"},
        desc:"Full-size supermarket with a bakery counter; nearest large grocery to the hotel.",
        hours:"Mo-Fr 07:15-19:00; Sa 07:15-18:00; Su off" },
      { name:"Adventure Park Summit", category:"attraction", lat:47.2980, lng:13.1810, drive_min:18, pass:true,
        desc:"Cable car to a mountain playground, alpine coaster and easy panorama loops.",
        hours:"May 1-Oct 31: 09:00-16:30", hours_note:"Weather-dependent" },
    ],
  },

  /* ============================ Base 2 ============================ */
  base2: {
    hotel: { name: "Sample Hotel — Village", lat: 47.4600, lng: 12.9100 },
    pois: [
      { name:"Wildlife Park", category:"animal", lat:47.4720, lng:12.9450, drive_min:14, pass:true,
        desc:"Native alpine animals on a stroller-friendly loop; feeding times midday.",
        hours:"Mo-Su 09:00-17:00" },
      { name:"Thermal Baths", category:"pool", lat:47.4510, lng:12.8880, drive_min:12,
        desc:"Indoor/outdoor thermal pools, water slides and a sauna world — top rainy-day option.",
        hours:"Mo-Su 10:00-21:00" },
      { name:"Trattoria Bella Vista", category:"restaurant", lat:47.4592, lng:12.9112, drive_min:3,
        desc:"Family-run Italian in the village center, big portions, garden seating.",
        hours:"Tu-Su 12:00-22:00; Mo off" },
      { name:"BILLA Supermarkt", category:"supermarket", lat:47.4585, lng:12.9138, drive_min:4, closed_days:{Su:"limited"},
        desc:"Central grocery with a deli; one of the few open (short hours) on Sundays.",
        hours:"Mo-Sa 07:30-19:00; Su 10:00-13:00" },
    ],
  },

};
